name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  S3_BUCKET_NAME: plant-hiker-bucket

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    # https://cheese10yun.github.io/github-action-1/
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./server
      
    - name: Build with Gradle
      run: ./gradlew build -x test #테스트스킵
      working-directory: ./server
      
    # build한 후 프로젝트를 압축합니다.
    - name: Make zip file
      run: zip -r ./plant-hiker.zip ./server
      shell: bash
      
    # Access Key와 Secret Access Key를 통해 권한을 확인합니다.
    # 아래 코드에 Access Key와 Secret Key를 직접 작성하지 않습니다.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }} # 등록한 Github Secret이 자동으로 불려옵니다.
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # 등록한 Github Secret이 자동으로 불려옵니다.
        aws-region: ap-northeast-2
        
    # 압축한 프로젝트를 S3로 전송합니다.
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./plant-hiker.zip s3://plant-hiker-bucket/plant-hiker.zip
